### ISSUE TITLE
Provide table functions

### ISSUE THREAD

**Issue by nineinchnick** [snowlift/trino-storage#129]
Table functions should be used instead of passing locations as table names.

Table functions also allow additional features, like:
* support case-sensitive locations
* users providing data types for some or all columns
* disabling automatic schema introspection or setting a limit, see #131 
* providing headers when making HTTP requests, somehow related to #92 and #24

**Comment by siripurapugopi** [comment]
Are these functions same as what I riased in #168 ?

**Comment by nineinchnick** [comment]
No
