### ISSUE TITLE
Design a safer way for reading local files

### ISSUE THREAD

**Issue by nineinchnick** [snowlift/trino-storage#130]
Reading files from the Trino nodes filesystem should not be permitted for security reasons.

Ideally, there should be a way to expose a local directory to the Trino clients. The Trino server would then request a file from the client. This would require changes in the Trino protocol.

Until the Trino protocol supports this, it should be possible to completely disable reading files from the local filesystem.

**Comment by nineinchnick** [comment]
This has been reported before in #12

**Comment by soenkeliebau** [comment]
Is this _solved_ by 3cf10d67d0254d08e3647480492a20979d151b27 ?

Arguably I'd say the default should be "false" - but that'd be breaking ..

**Comment by nineinchnick** [comment]
@soenkeliebau yes. This is exactly why I set the default to `true` to avoid making this a breaking change, but we should consider changing this default.
