### ISSUE TITLE
Catalog 'storage' does not exist

### ISSUE THREAD

**Issue by siripurapugopi** [snowlift/trino-storage#165]
I have copied the generated jar files into ${TRINO_HOME}/lib. When I open superset getting below error:

**Trino Error
trino error: line 1:15: Catalog 'storage' does not exist

This may be triggered by:
Issue 1002 - The database returned an unexpected error. 

See less**

**Comment by ebyhr** [comment]
Please put a catalog property file. Just deploying jar files is insufficient.

**Comment by siripurapugopi** [comment]
Any sample file for storage catalog?
