### ISSUE TITLE
Use Airlift's HTTP client in StorageClient for proxy support

### ISSUE THREAD

**Issue by nineinchnick** [snowlift/trino-storage#169]
The `StorageClient` class currently uses `javax.net.ssl.HttpsURLConnection`. If it were using Airlift's HTTP client, it would be possible to configure a proxy for it.

**Comment by metalshanked** [comment]
@nineinchnick @ebyhr : apologies for the basic question
how do we configure the connector properties to use the HTTP proxy setting? I do not want to have a global HTTP_PROXY variable

Thanks!

**Comment by ebyhr** [comment]
@metalshanked There's `http-client.http-proxy` config property. See  
https://github.com/airlift/airlift/blob/master/http-client/src/main/java/io/airlift/http/client/HttpClientConfig.java for more details.

**Comment by metalshanked** [comment]
> @metalshanked There's `http-client.http-proxy` config property. See https://github.com/airlift/airlift/blob/master/http-client/src/main/java/io/airlift/http/client/HttpClientConfig.java for more details.

Thanks!  Is there a way to set a "no-proxy" as well to bypass certain uri's from proxying ?

**Comment by ebyhr** [comment]
No.

**Comment by metalshanked** [comment]
> No.

Sure no worries. Thanks again
