### ISSUE TITLE
420 getting Table does not exist with csv and excel schema

### ISSUE THREAD

**Issue by wAVeckx** [snowlift/trino-storage#199]
Using the schema of txt works. But if I switch to csv or excel the error appears. 

Works:
SELECT * FROM
storage.txt."https://raw.githubusercontent.com/snowlift/trino-storage/master/src/test/resources/example-data/sample.xlsx";
Result:
Provides column named value with encoded data: PK [Content_Types].xml

Errors:
SELECT * FROM
storage.excel."https://raw.githubusercontent.com/snowlift/trino-storage/master/src/test/resources/example-data/sample.xlsx"
Result:
 Table 'storage.excel.https://raw.githubusercontent.com/snowlift/trino-storage/master/src/test/resources/example-data/sample.xlsx' does not exist

**Comment by nineinchnick** [comment]
When reading CSV files, the first row should be column names. `orders-1.csv` has an empty value in the last column in the first row, that's why it's throwing an exception.

The other issue with excel files is fixed by #206
