### ISSUE TITLE
Tests fail on case-sensitive systems if path has upper-case characters

### ISSUE THREAD

**Issue by nightkr** [snowlift/trino-storage#239]
```
n@emeritus:~/Documents/stackable/trino-storage$ mvn test
[snip]
java.io.UncheckedIOException: Failed to open stream for file:/home/n/documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv
        at org.ebyhr.trino.storage.StorageClient.getInputStream(StorageClient.java:115)
        at org.ebyhr.trino.storage.StorageClient.lambda$getTable$0(StorageClient.java:84)
        at org.ebyhr.trino.storage.operator.CsvPlugin.getFields(CsvPlugin.java:41)
        at org.ebyhr.trino.storage.StorageClient.getTable(StorageClient.java:84)
        at org.ebyhr.trino.storage.StorageMetadata.getStorageTableMetadata(StorageMetadata.java:165)
        at org.ebyhr.trino.storage.StorageMetadata.getTableMetadata(StorageMetadata.java:88)
[snip]
n@emeritus:~/Documents/stackable/trino-storage$ cat /home/n/documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv
cat: /home/n/documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv: No such file or directory
n@emeritus:~/Documents/stackable/trino-storage$ cat /home/n/Documents/stackable/trino-storage/target/test-classes/example-data/numbers-2.csv
ten, 10
eleven, 11
twelve, 12
```

**Comment by nightkr** [comment]
This seems to come down to that `SchemaTableName` force-lowercases the table name: https://github.com/trinodb/trino/blob/7530cd5a8a171742ef83159e3fc90f6913d4435a/core/trino-spi/src/main/java/io/trino/spi/connector/SchemaTableName.java#L37

**Comment by nineinchnick** [comment]
Trino doesn't support case-sensitive table names, and using paths as table names is a hack. One of the way to address this was the introduction of [table functions](https://github.com/snowlift/trino-storage#table-functions). I'm not sure if we'll support running all tests because of Trino limitations, and we might remove table support at some point in favor of table functions.

**Comment by nightkr** [comment]
It actually looks like it _almost_ works, the problem "only" comes in once `getTableMetadata` converts the `StorageTableHandle` into a `SchemaTableName` in https://github.com/snowlift/trino-storage/blob/8b697ba61486cd0cbcebdf17ce0d1a5a25a89e16/src/main/java/org/ebyhr/trino/storage/StorageMetadata.java#L86.

If we encode it in something case-preserving (like base16) then we can decode it before reading without affecting the public API: https://gist.github.com/nightkr/e05679be6b63c2b9b59876274af010d7

**Comment by nightkr** [comment]
(I'm not saying that's a reasonable way to do it, but it's definitely possible, heh.)

**Comment by nineinchnick** [comment]
We could delay constructing `SchemaTableName` and pass the original name to `getStorageTableMetadata()`. It's a private method. Would you like to open a PR?

**Comment by nightkr** [comment]
That's true, I overfixated on the `ConnectorTableMetadata` eventually returning it. Sure.
