### ISSUE TITLE
Can not query storage catalog when Fault Tolerant Execution is activated

### ISSUE THREAD

**Issue by alaturqua** [snowlift/trino-storage#359]
Currently this connector causing issues, if FTE is enabled on the trino cluster. Queries directing to this catalog fail.

**Comment by nineinchnick** [comment]
What's the error you're getting?

**Comment by alaturqua** [comment]
Do you think, this can be fixed/implemented for this connector? It would be great if queries could still read from this catalog, while FTE is enabled.

**Comment by nineinchnick** [comment]
Fixed in 37630ef8bfbad5e2978957dcd5407d63e99ca3b0, will release a new version once Trino 465 is out.
