### ISSUE TITLE
.git directory is not found

### ISSUE THREAD

**Issue by Piyushency** [snowlift/trino-storage#83]
When running the command `./mvnw test` it gives the following error

<pre>[<font color="#CC0000"><b>ERROR</b></font>] Failed to execute goal <font color="#4E9A06">pl.project13.maven:git-commit-id-plugin:4.0.5:revision</font> <b>(default)</b> on project <font color="#06989A">trino-storage</font>: <font color="#CC0000"><b>.git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml</b></font> -&gt; <b>[Help 1]</b>
[<font color="#CC0000"><b>ERROR</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[<font color="#CC0000"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#CC0000"><b>ERROR</b></font>] 
[<font color="#CC0000"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#CC0000"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
</pre>

**Comment by ebyhr** [comment]
Please use git clone instead of downloading only source code.

**Comment by Piyushency** [comment]
Build was successful. How to use it with Trino? Where to copy the jar files in trino-storage/target as mentioned in Deploy section?
