### ISSUE TITLE
How to use it with trino after building it?

### ISSUE THREAD

**Issue by almiodescartes** [snowlift/trino-storage#86]
Steps mentioned to use it with trino are unclear. Please mention the steps to follow after successfully building it using ./mvnw clean install -DskipTests. What files are to be added to trino-server directory? Do we have to add storage.properties file in etc/catalog just like other connectors?

**Comment by ebyhr** [comment]
> Do we have to add storage.properties file in etc/catalog just like other connectors?

Yes.
