### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by almiodescartes** [snowlift/trino-storage#88]
I am trying to access a csv file in my local storage. I used the below command on trino cli
SELECT * FROM
storage.csv."file:///home/<USER>/test.csv";

However, it gives an error that the file does not exist even though it is there.
`Query 20220502_065912_00014_23th2 failed: line 2:1: Table 'storage.csv.file:///home/almio/test.csv' does not exist`

**Comment by ebyhr** [comment]
@almiodescartes Please share more details when filing an issue, config properties, directory status, query, full stacktrace.

**Comment by almiodescartes** [comment]
The issue is resolved. The name of the file was Test.csv. Using SELECT * FROM storage.csv."file:///home/almio/Test.csv"; does not seem to work but renaming the file with lowercase does the trick. I guess this issue should be handled in future versions.

**Comment by ebyhr** [comment]
> I guess this issue should be handled in future versions.

It's an engine issue rather than connectors. We won't add support for case insensitive matching in this connector.
