### ISSUE TITLE
any plans to make it support generic http?

### ISSUE THREAD

**Issue by DeoLeung** [snowlift/trino-storage#92]
Hi,
seems like this connector could query an api endpoint and get response as json

it's there any plan to extend it a bit support sending headers/body and get a bit more result like status code, headers, content type?

**Comment by nineinchnick** [comment]
This is not meant to be a generic HTTP connector, only to read local or possibly remote JSON files. But it's not supposed to handle any authentication for remote files.

You could try writing a custom connector for a specific HTTP API yourself. Check out this one for more examples: https://github.com/nineinchnick/trino-rest
